name: ✨ Feature Request
description: Request a new feature for authenticus.
labels: [feature]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what feature you want to be implemented.
      placeholder: I'm always frustrated when..., A good addition would be..., Can you add a preset for...
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
