name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: 18

      - uses: 'denoland/setup-deno@v1'
        with:
          deno-version: 'v1.x'

      - name: 'Grab Version'
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: 'Build Package'
        run: 'deno task build'

      - uses: 'JS-DevTools/npm-publish@v2'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './cache'
      
      - name: 'Publish Release'
        uses: 'actions/github-script@v6'
        with:
          script: |
            const { readFile } = require('fs/promises')
              
            let changelog = await readFile('./changelog.md', { encoding: 'utf-8' })
              
            const startIndex = changelog.indexOf(`## [${process.env.TAG}]`) + `## [${process.env.TAG}](https://github.com/azurystudio/authenticus/releases/tag/${process.env.TAG})\n\n`.length

            changelog = changelog.substring(startIndex)

            const endIndex = changelog.indexOf('\n\n## [')

            changelog = changelog.substring(0, endIndex < 0 ? undefined : endIndex)

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG,
              name: process.env.TAG,
              body: changelog,
              draft: false,
              prerelease: false
            })
